//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int NUM_CC { get; set; }
        public string NomeProprio { get; set; }
        public string NomeApelido { get; set; }
        public string Email { get; set; }
        public Nullable<int> Contacto { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Morada { get; set; }
        public string Foto { get; set; }
    }
}
